![data-x](http://oi64.tinypic.com/o858n4.jpg)

---
# Pandas Introduction 
### with Stock Data and Correlation Examples


**Author list:** Ikhlaq Sidhu & Alexander Fred Ojala

**References / Sources:** 
Includes examples from Wes McKinney and the 10min intro to Pandas


**License Agreement:** Feel free to do whatever you want with this code

___

## What Does Pandas Do?
<img src="https://github.com/ikhlaqsidhu/data-x/raw/master/imgsource/pandas-p1.jpg">

## What is a Pandas Table Object?
<img src="https://github.com/ikhlaqsidhu/data-x/raw/master/imgsource/pandas-p2.jpg">


## This table is a dictionary of sequences (like np arrays)
<img src="https://github.com/ikhlaqsidhu/data-x/raw/master/imgsource/pandas-p3.jpg">


# Import packages

In [1]:
# import packages

import pandas as pd

# Extra packages
import numpy as np
import matplotlib.pyplot as plt # for plotting
import seaborn as sns # for plotting and styling

# jupyter notebook magic to display plots in output
%matplotlib inline

plt.rcParams['figure.figsize'] = (10,6) # make the plots bigger

# Part 1
### Simple creation and manipulation of Pandas objects
**Key Points:** Pandas has two / three main data types:
* Series (similar to numpy arrays, but with index)
* DataFrames (table or spreadsheet with Series in the columns)
* Panels (3D version of DataFrame, not as common)

### It is easy to create a DataFrame

### We use `pd.DataFrame(**inputs**)` and can insert almost any data type as an argument

**Function:** `pd.DataFrame(data=None, index=None, columns=None, dtype=None, copy=False)`

Input data ca be a numpy ndarray (structured or homogeneous), dict, or DataFrame. 
Dict can contain Series, arrays, constants, or list-like objects as the values.

In [2]:
# Try it with an array
np.random.seed(0) # set seed for reproducibility

a1 = np.array(np.random.randn(3))
a2 = np.array(np.random.randn(3))
a3 = np.array(np.random.randn(3))

print (a1)
print (a2)
print (a3)

[ 1.76405235  0.40015721  0.97873798]
[ 2.2408932   1.86755799 -0.97727788]
[ 0.95008842 -0.15135721 -0.10321885]


In [3]:
print(type(a1))

<class 'numpy.ndarray'>


In [4]:
# Create our first DataFrame w/ an np.array - it becomes a column
df0 = pd.DataFrame(a1)
print ("This is a", type(df0), ':')
df0

This is a <class 'pandas.core.frame.DataFrame'> :


0
0  1.764052
1  0.400157
2  0.978738

In [ ]:
print(df0) # difference when you print and output of the last row

In [5]:
# DataFrame from list of np.arrays

df0 = pd.DataFrame([a1, a2, a3])
df0

# notice that there is no column label, only integer values,
# and the index is set automatically

0         1         2
0  1.764052  0.400157  0.978738
1  2.240893  1.867558 -0.977278
2  0.950088 -0.151357 -0.103219

In [6]:
# DataFrame from 2D np.array

np.random.seed(0)

ax = np.array(np.random.randn(9)).reshape(3,3)
ax

array([[ 1.76405235,  0.40015721,  0.97873798],
       [ 2.2408932 ,  1.86755799, -0.97727788],
       [ 0.95008842, -0.15135721, -0.10321885]])

In [7]:
df0 = pd.DataFrame(ax,columns=['rand_normal_1','Random Again','Third'],
                   index=[100,200,99]) # we can also assign columns and indices, sizes have to match
df0

rand_normal_1  Random Again     Third
100       1.764052      0.400157  0.978738
200       2.240893      1.867558 -0.977278
99        0.950088     -0.151357 -0.103219

In [8]:
# DataFrame from a Dictionary

dict1 = {'A':a1, 'B':a2}
df1 = pd.DataFrame(dict1) 
df1
# note that we now have columns without assignment

A         B
0  1.764052  2.240893
1  0.400157  1.867558
2  0.978738 -0.977278

In [9]:
# We can easily add another column (just as you add values to a dictionary)
df1['C']=a3
df1

A         B         C
0  1.764052  2.240893  0.950088
1  0.400157  1.867558 -0.151357
2  0.978738 -0.977278 -0.103219

In [10]:
# We can add a list with strings and ints as a column 
df1['L'] = ["List", 3, "words"]
print ("The column L is a ",type (df1['L']))
df1

The column L is a  <class 'pandas.core.series.Series'>


A         B         C      L
0  1.764052  2.240893  0.950088   List
1  0.400157  1.867558 -0.151357      3
2  0.978738 -0.977278 -0.103219  words

In [11]:
print(df1['L'][0])
print(type(df1['L'][0]))
print(df1['L'][1])
print(type(df1['L'][1])) # datatype not upcasted / changed as in numpy

List
<class 'str'>
3
<class 'int'>


# Pandas Series object
### Like an np.array, but we can combine data types and it has its own index
Note: Every column in a DataFrame is a Series

In [12]:
print(df1['L'])
print()
print(type(df1['L']))

0     List
1        3
2    words
Name: L, dtype: object

<class 'pandas.core.series.Series'>


In [13]:
# Create a Series from a Python list
s = pd.Series([1,np.nan,3]) # automatic index, 0,1,2...
s2 = pd.Series([2, 3, 4], index = ['a','b','c']) #specific index
print (s)
print()
print (s2)

0    1.0
1    NaN
2    3.0
dtype: float64

a    2
b    3
c    4
dtype: int64


In [15]:
# We can add the Series s to the DataFrame above as column S
df1['S'] = s
df1

A         B         C      L    S
0  1.764052  2.240893  0.950088   List  1.0
1  0.400157  1.867558 -0.151357      3  NaN
2  0.978738 -0.977278 -0.103219  words  3.0

In [18]:
# What happens if we use Series s2 
# which has a different index?
df1['S2']=s2
df1

A         B         C      L    S  S2
0  1.764052  2.240893  0.950088   List  1.0 NaN
1  0.400157  1.867558 -0.151357      3  NaN NaN
2  0.978738 -0.977278 -0.103219  words  3.0 NaN

In [19]:
# possible fix
# s2_new=s2.reset_index().drop('index',axis=1)
# df1['S2'] = s2_new

# or
# s2.index = df1.index
# df1['S2'] = s2

# or
# df1['S2'] = list(s2) # because lists don't have any indices

In [20]:
# But if we create a new dataframe with s2, 
# we can add the data but with the new index
df2 = pd.DataFrame(s2,columns=['S2'])
df2

S2
a   2
b   3
c   4

In [21]:
df2['A']= a1
df2['B']=a2
df2['C']=a3
df2

S2         A         B         C
a   2  1.764052  2.240893  0.950088
b   3  0.400157  1.867558 -0.151357
c   4  0.978738 -0.977278 -0.103219

In [22]:
# You can extract rows by position or label
print (df2[1:3]) # second and third row
print()
print (df2['a':'b']) # from a to b inclusive

   S2         A         B         C
b   3  0.400157  1.867558 -0.151357
c   4  0.978738 -0.977278 -0.103219

   S2         A         B         C
a   2  1.764052  2.240893  0.950088
b   3  0.400157  1.867558 -0.151357


In [23]:
# Back to df1
df1

A         B         C      L    S  S2
0  1.764052  2.240893  0.950088   List  1.0 NaN
1  0.400157  1.867558 -0.151357      3  NaN NaN
2  0.978738 -0.977278 -0.103219  words  3.0 NaN

In [24]:
# We can also rename columns
df1 = df1.rename(columns = {'L':'Renamed'})
df1

A         B         C Renamed    S  S2
0  1.764052  2.240893  0.950088    List  1.0 NaN
1  0.400157  1.867558 -0.151357       3  NaN NaN
2  0.978738 -0.977278 -0.103219   words  3.0 NaN

In [25]:
# We can delete columns
del df1['S2']
df1

A         B         C Renamed    S
0  1.764052  2.240893  0.950088    List  1.0
1  0.400157  1.867558 -0.151357       3  NaN
2  0.978738 -0.977278 -0.103219   words  3.0

In [26]:
# or drop columns
df1.drop('A',axis=1) # does not change df1 if we don't set inplace=True

B         C Renamed    S
0  2.240893  0.950088    List  1.0
1  1.867558 -0.151357       3  NaN
2 -0.977278 -0.103219   words  3.0

In [27]:
df1

A         B         C Renamed    S
0  1.764052  2.240893  0.950088    List  1.0
1  0.400157  1.867558 -0.151357       3  NaN
2  0.978738 -0.977278 -0.103219   words  3.0

In [28]:
# or drop rows
df1.drop(0)

A         B         C Renamed    S
1  0.400157  1.867558 -0.151357       3  NaN
2  0.978738 -0.977278 -0.103219   words  3.0

In [29]:
# Example: view only one column
df1['A']

0    1.764052
1    0.400157
2    0.978738
Name: A, dtype: float64

In [30]:
# Or view several column
df1[['A','C']]

A         C
0  1.764052  0.950088
1  0.400157 -0.151357
2  0.978738 -0.103219

# Other ways of slicing
In the 10 min Pandas Guide, you will see many ways to view, slice a dataframe

* view/slice by rows, eg `df[1:3]`, etc.

* view by index location, see `df.iloc` (iloc)

* view by ranges of labels, ie index label 2 to 5, or dates feb 3 to feb 25, see `df.loc` (loc)
 
* view a single row by the index `df.xs` (xs) or `df.ix` (ix)

* filtering rows that have certain conditions
* add column
* add row

* How to change the index

and more...

In [31]:
print (df1[0:2])  # ok
# df1[1]  # not ok

          A         B         C Renamed    S
0  1.764052  2.240893  0.950088    List  1.0
1  0.400157  1.867558 -0.151357       3  NaN


In [32]:
df1.loc[0,['A','B','S']] # first row, three columns

A    1.76405
B    2.24089
S          1
Name: 0, dtype: object

In [33]:
print (df1[0:2][0:1]) # slice of the DataFrame returned

          A         B         C Renamed    S
0  1.764052  2.240893  0.950088    List  1.0


# Part 2
## Finance example: Large Data Frames

### Now, lets get some data in CSV format.

See https://www.quantshare.com/sa-43-10-ways-to-download-historical-stock-quotes-data-for-free


In [ ]:
# We can download data from the web by using pd.read_csv
# A CSV file is a comma seperated file
# We can use this 'pd.read_csv' method with urls that host csv files

dfg = pd.read_csv('https://www.google.com/finance/historical?output=csv&q=googl') # Google stock data
dfa = pd.read_csv('https://www.google.com/finance/historical?output=csv&q=aapl') # Apple stock data

In [ ]:
dfg.head() # show first five values

In [ ]:
dfg.tail(3) # last three

In [ ]:
dfg.columns # returns columns, can be used to loop over

In [ ]:
dfg.index # return

# Convert the index to pandas datetime object

In [ ]:
type(dfg['Date'][0])

In [ ]:
dfg.index = pd.to_datetime(dfg['Date']) # set index

In [ ]:
dfg.drop(['Date'],axis=1,inplace=True)

In [ ]:
dfg.head()

In [ ]:
print(type(dfg.index[0]))
dfg.index[0]

In [ ]:
dfg['2017-04-07':'2017-04-01']

# Attributes & general statitics of a Pandas DataFrame

In [ ]:
dfg.shape # 249 business days last year

In [ ]:
dfg.columns

In [ ]:
dfg.size

In [ ]:
# Some general statistics

dfg.describe()

In [ ]:
# Boolean indexing
dfg['Open'][dfg['Open']>980] # check what dates the opening

In [ ]:
# Check where Open, High, Low and Close where greater than 980
dfg[dfg>980].drop('Volume',axis=1).head(3)

In [ ]:
# drop na
dfg[dfg>980].drop('Volume',axis=1).dropna().head(3)

In [ ]:
# If you want the values in an np array
npg = dfg.values
print(type(npg))
print()
npg

### Selecting or Viewing Data within a DataFrame
Note: While standard Python / Numpy expressions for selecting and setting are intuitive and come in handy for interactive work, for production code, we recommend the optimized pandas data access methods, .at, .iat, .loc, .iloc and .ix. (from 10 min guide to Pandas)


In [ ]:
# Lets print the five first Close prices for Google
# This is a new Series (like a new table)
dfg['Close'][0:5]

In [ ]:
# Lets print the 2 column, and top 3 values
dfg[['Close','High']][0:3]

In [ ]:
# A slice: by rows (row numbers)
dfg[1:5] # 2nd to 5th element

## .loc()

In [ ]:
# Getting a cross section with .loc - BY VALUES of the index and columns
# df.loc[a:b, x:y], by rows and column location

# Note: You have to know indices and columns

dfg.loc['2017-08-31':'2017-08-21','Open':'Close']

## .iloc()

In [ ]:
dfg.columns

In [ ]:
# .iloc slicing at specific location - BY POSITION in the table
# Recall:
# dfg[a:b] by rows
# dfg[[col]] or df[[col1, col2]] by columns
# df.loc[a:b, x:y], by index and column values + location
# df.iloc[3:5,0:2], numeric position in table

dfg.iloc[1:4,3:5] # 2nd to 4th row, 4th to 5th column

In [ ]:
# Data only from row with index value '3'
print (dfg.iloc[3])

In [ ]:
# iloc will accept 'lists' of position numbers
dfg.iloc[[1,2,4],[0,2]]

In [ ]:
# iloc will accept a range with ':', just like numpy
dfg.iloc[1:3,:]

In [ ]:
# Can also return specific value
print (dfg.iloc[2,1])
# same as above but faster for one single scaler value
print (dfg.iat[2,1])

In [ ]:
?dfg.iat() #fast integer location scalar accessor

### More Basic Statistics

In [ ]:
# A quick way to get statistics
dfg.describe()
# dfg.describe()['A'][1]
# dfg.describe()[2:3]

In [ ]:
dfg.describe().loc[['mean','std'],['High','Low']]

In [ ]:
dfg.head()

In [ ]:
# We can change the index sorting
dfg.sort_index(axis=0, ascending=True).head() # starts a year ago

In [ ]:
# sort by value
dfg[0:5].sort_values(by='Open')

In [ ]:
dfg.describe()[2:3]

In [ ]:
# Transpose in Pandas
dfg.describe()[2:3].T

### Masks and Boolean Indexing

In [ ]:
dfg[0:10]

In [ ]:
# mask 1
mg1 = dfg['Open'][0:10]>941
print (mg1)
# dfg.Open[0:10]>941    # same thing

In [ ]:
dfg['Open'][0:10][dfg['Open']>941]
# shows only rows with opening price greater than 941

In [ ]:
# mask 2
mg2 = dfg[0:10]>941
mg2
# replaces every value in the entire table with NaN if the value of below 941

In [ ]:
dfg[dfg>941].head(10)

In [ ]:
# we can also drop all NaN values
dfg[dfg>941].head(10).dropna()

In [ ]:
# another way to filter is with isin()
# syntax only
# df2[df2['E'].isin(['two','four'])]

In [ ]:
# like Numpy, sometimes you need an actual copy, not a view or slice of the same data
dfg_same = dfg
dfg_same is dfg

In [ ]:
dfg2 = dfg.copy()
dfg2 is dfg

### Setting Values


In [ ]:
# Recall
dfg.head(4)

In [ ]:
# All the ways to view (by location, by index, iat, etc) 
# can also be used to set values
# good for data normalization

dfg['Volume'] = dfg['Volume']/1000.0
dfg.head(4)

In [ ]:
dfg['Volume'] = 9999
print(dfg.head(10))

In [ ]:
# Change specific entry
dfg.iat[0,1] = 0
dfg.head(3)

In [ ]:
# Comments on dropping and filling NaN values
# A view where we drop any rows with value NnN
# dfg.dropna(how='any')  # this would be used to drop rows with Nan
# df1.fillna(value=5)    # this would be used to fill NaN values with 5

### More Statistics and Operations

In [ ]:
# mean by column, also try var() for variance
dfg.mean()   

In [ ]:
dfg[0:5].mean(1) # row means of first five rows
# dfg.mean(axis = 1)

In [ ]:
# Use the apply method to perform calculations on every element
dfg2[0:10].apply(np.cumsum)

# PlotCorrelation
### Load several stocks

In [ ]:
# Reload
dfg = pd.read_csv('https://www.google.com/finance/historical?output=csv&q=goog')
dfa = pd.read_csv('https://www.google.com/finance/historical?output=csv&q=aapl')
dfm = pd.read_csv('https://www.google.com/finance/historical?output=csv&q=msft')
dfn = pd.read_csv('https://www.google.com/finance/historical?output=csv&q=nke')
dfb = pd.read_csv('https://www.google.com/finance/historical?output=csv&q=ba')

In [ ]:
print (dfb.head())

In [ ]:
# Rename columns
dfg = dfg.rename(columns = {'Close':'GOOG'})
#print (dfg.head())

dfa = dfa.rename(columns = {'Close':'AAPL'})
#print (dfa.head())

dfm = dfm.rename(columns = {'Close':'MSFT'})
#print (dfm.head())

dfn = dfn.rename(columns = {'Close':'NKE'})
#print (dfn.head())

dfb = dfb.rename(columns = {'Close':'BA'})

In [ ]:
dfb.head(2)

In [ ]:
# Lets merge some tables
# They will all merge on the common column Date

df = dfg[['Date','GOOG']].merge(dfa[['Date','AAPL']])
df = df.merge(dfm[['Date','MSFT']])
#df = df.merge(dfd[['Date','DIS']])
df = df.merge(dfn[['Date','NKE']])
df = df.merge(dfb[['Date','BA']])

df.head()

In [ ]:
df['Date'] = pd.to_datetime(df['Date'])
df = df.set_index('Date')
df.head()

In [ ]:
df.plot()

In [ ]:
df['2017'][['AAPL','MSFT']].plot()

In [ ]:
# show a correlation matrix (pearson)
crl = df.corr()
crl

In [ ]:
crl.sort_values(by='GOOG',ascending=False)